### ISSUE TITLE
Image handling

### ISSUE THREAD

**Issue by hartpableo** [rckash/marameo-1#2]
Currently, curved images like this are rendered as being rendered as png images on the site.

Please switch this to jpg/jpeg format and make the curved border effect via css.

**Reason:**
PNG format is heavier/larger compared to **JPG/JPEG/WEBP** formats. So it is a good and advisable practice to keep the images optimized. Lighter assets means faster loading time, and faster loading time means better user experience for the site visitors.

![image](https://github.com/rckash/marameo-1/assets/84109447/f14b08d7-1d76-40ad-b73a-8357306675dc)

**Comment by rckash** [comment]
Thank you. I will go ahead and do so.

**Comment by hartpableo** [comment]
@rckash please hold this until tomorrow. As you would need the Dev Mode on Figma for this but looks like you guys don't have access to it. I'll talk more about this at the meeting tomorrow.
