### ISSUE TITLE
Anchor tags vs. buttons

### ISSUE THREAD

**Issue by hartpableo** [rckash/marameo-1#3]
![image](https://github.com/user-attachments/assets/c76ac062-8a99-4023-98ec-e189ae8ded17)

For "buttons" that are going to be having links, use the anchor tag.

**Comment by hartpableo** [comment]
![image](https://github.com/user-attachments/assets/a1f4c604-9b09-4628-84f3-a59aa6263f2b)

In this use-case on the other hand, a hamburger menu button is not really going to contain a link. So, a button element is the right element to use.

**Comment by rckash** [comment]
> ![image](https://private-user-images.githubusercontent.com/84109447/353107821-a1f4c604-9b09-4628-84f3-a59aa6263f2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTUxMDcsIm5iZiI6MTcyMjMxNDgwNywicGF0aCI6Ii84NDEwOTQ0Ny8zNTMxMDc4MjEtYTFmNGM2MDQtOWIwOS00NjI4LTg0ZjMtYTU5YWE2MjYzZjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA0NDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MGM2MDA4MjhlZTY4YmNlMWVhZGVmOGEwYjBiNjQ1MWJkZWE3OGVkMjMwZDlmZDQzZDAxMjZlY2E0NGY5NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e_qz2tjo5XSLVtdZM6-l23sZaOroMXYiZRg-36eOVe4)
> 
> In this use-case on the other hand, a hamburger menu button is not really going to contain a link. So, a element is the right element to use.

To be clear, I should be using a button element for my hamburger or anchor element?

**Comment by hartpableo** [comment]
@rckash sorry for the typo...

- Anchor Tags or < a > for "buttons" that have links
- Button tags or < button > for "buttons" that are not expected to have links and are only intended for interactivity like a hamburger button
