### ISSUE TITLE
Multiple anchor tags in a single component

### ISSUE THREAD

**Issue by hartpableo** [rckash/marameo-1#4]
![image](https://github.com/user-attachments/assets/ac22a73a-8db8-4e56-abb4-694eab92dd7c)

As much as possible, keep the number of anchor tags per card to just one.

Let me know if you need some tips here.

**Comment by rckash** [comment]
yes some tips would be very helpful, I am not sure if I should put everything inside an anchor tag or however.

**Comment by hartpableo** [comment]
@rckash you can add an empty anchor tag at the end and make it absolute with inset of 0.

for best practice, there should be a screen reader text inside this anchor tag (not critical for now).

z-index might also be necessary to make sure your anchor tag is on top of all the other elements. 

the card component must be relative so that the anchor tag wont overflow from it.
